included:
    - SwiftRequestBuilder 

disabled_rules:
- comment_spacing
- trailing_whitespace
- todo

opt_in_rules:
- force_unwrapping
- vertical_whitespace_opening_braces
- vertical_whitespace_closing_braces
- vertical_whitespace_between_cases

cyclomatic_complexity:
  warning: 5
  ignores_case_statements: true

identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - Current

nesting:
  type_level:
    warning: 3

